export const sampleProject = {
  id: "project-proof",
  revision: 1,
  name: "UOK Gantt Proof",
  status: "active",
  start: "2026-08-01",
  end: "2026-08-20",
  target_finish: "2026-08-20",
  calculated_finish: "2026-08-13",
  updated_at: "2026-08-01T00:00:00Z",
};

export const sampleSchedule = {
  project: sampleProject,
  capabilities: { read: true, edit: true, baseline_create: true, level: true, link: true, gate_approve: true, admin: true, review_only: false },
  task_flow: {
    schema_version: 1,
    statuses: [
      { status: "planned", display_label: "Planned", allowed_transitions: ["in_progress", "blocked", "complete"] },
      { status: "in_progress", display_label: "In progress", allowed_transitions: ["planned", "blocked", "complete"] },
      { status: "blocked", display_label: "Blocked", allowed_transitions: ["planned", "in_progress", "complete"] },
      { status: "complete", display_label: "Complete", allowed_transitions: ["planned", "in_progress"] },
    ],
  },
  validation: { ok: true, violations: [], warnings: ["Planner is allocated 120% against 100% capacity on 2026-08-06"] },
  calculation: {
    engine_version: "uok-cpm-2",
    project_start: "2026-08-03",
    calculated_finish: "2026-08-13",
    target_finish: "2026-08-20",
    target_variance_days: -5,
    independent_validation: { ok: true, violations: [] },
  },
  tasks: [
    {
      id: "task-summary",
      project_id: sampleProject.id,
      version: 1,
      parent_task_id: null,
      wbs: "1",
      title: "Pilot delivery",
      task_type: "summary",
      status: "planned",
      start: "2026-08-01",
      end: "2026-08-13",
      duration_days: 9,
      progress: 20,
      sort_order: 0,
      critical: false,
      total_slack_days: 0,
      baseline_start: "2026-08-01",
      baseline_end: "2026-08-12",
      start_variance_days: 0,
      end_variance_days: 1,
    },
    {
      id: "task-1",
      project_id: sampleProject.id,
      version: 1,
      parent_task_id: "task-summary",
      wbs: "1.1",
      title: "Define schedule scope",
      task_type: "task",
      status: "planned",
      start: "2026-08-01",
      end: "2026-08-03",
      duration_days: 3,
      progress: 40,
      sort_order: 1,
      critical: true,
      total_slack_days: 0,
      baseline_start: "2026-08-01",
      baseline_end: "2026-08-03",
      start_variance_days: 0,
      end_variance_days: 0,
      scheduling_mode: "manual",
      constraint_type: "must_start_on",
      constraint_date: "2026-08-01",
    },
    {
      id: "task-2",
      project_id: sampleProject.id,
      version: 1,
      parent_task_id: "task-summary",
      wbs: "1.2",
      title: "Build integrated Gantt with dependency validation",
      task_type: "task",
      status: "planned",
      start: "2026-08-04",
      end: "2026-08-10",
      duration_days: 7,
      progress: 0,
      sort_order: 2,
      critical: true,
      total_slack_days: 0,
      baseline_start: "2026-08-04",
      baseline_end: "2026-08-09",
      start_variance_days: 0,
      end_variance_days: 1,
    },
    {
      id: "task-3",
      project_id: sampleProject.id,
      version: 1,
      parent_task_id: "task-summary",
      wbs: "1.3",
      title: "Pilot review milestone",
      task_type: "milestone",
      status: "planned",
      start: "2026-08-13",
      end: "2026-08-13",
      duration_days: 0,
      progress: 0,
      sort_order: 3,
      critical: true,
      total_slack_days: 0,
      baseline_start: "2026-08-12",
      baseline_end: "2026-08-12",
      start_variance_days: 1,
      end_variance_days: 1,
      participant_ids: ["party-proof"],
      participant_roles: ["approver"],
      readiness: { ready: false, required_count: 1, blocking_count: 1, blocking_requirement_ids: ["requirement-proof"] },
    },
  ],
  dependencies: [
    {
      id: "dep-1",
      project_id: sampleProject.id,
      predecessor_task_id: "task-1",
      successor_task_id: "task-2",
      dependency_type: "finish_to_start",
      lag_days: 1,
    },
  ],
  calendar: { name: "Standard", working_days: [1, 2, 3, 4, 5], holidays: ["2026-08-14"], ignored_periods: [{ start: "2026-08-17", end: "2026-08-18" }] },
  resources: [{
    id: "resource-1", project_id: sampleProject.id, name: "Planner", role: "Scheduling",
    resource_type: "human", capacity_value: 1, capacity_unit: "fte",
    canonical_target_kind: null, canonical_target_id: null, canonical_resolution: null,
    effective_start: null, effective_end: null, calendar: null,
  }],
  assignments: [{ id: "assignment-1", task_id: "task-2", resource_id: "resource-1", allocation_percent: 120 }],
  links: [{
    id: "link-thread-proof",
    project_id: sampleProject.id,
    task_id: "task-1",
    scope_type: "task",
    relationship: "discussed_in",
    blocking: false,
    target: { kind: "communication_thread", id: "thread-proof", resolver: "kconnect.thread", resolver_version: "1" },
    resolution: { status: "ready", display_label: "Pilot K Connect room", status_summary: "Communication thread is open.", checked_at: "2026-08-01T00:00:00Z", open_path: "/?view=communications&thread_id=thread-proof" },
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
  }],
  participants: [{
    id: "participant-proof",
    project_id: sampleProject.id,
    task_id: "task-3",
    role: "approver",
    source_module: "contacts.core",
    party: { id: "party-proof", resolver: "contacts.party", resolver_version: "1" },
    resolution: { status: "ready", display_label: "Pilot approver", status_summary: "Party is active.", checked_at: "2026-08-01T00:00:00Z", open_path: "/?view=contacts&party_id=party-proof" },
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
  }],
  requirements: [{
    id: "requirement-proof",
    project_id: sampleProject.id,
    task_id: "task-3",
    requirement_type: "approval",
    title: "Pilot execution approval",
    state: "under_review",
    required: true,
    blocking: true,
    target_link_id: null,
    target_link_state: "unlinked",
    due: "2026-08-13",
    decision_reason: null,
    decided_by_actor_id: null,
    decided_at: null,
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
  }],
  readiness: { ready: false, required_count: 1, blocking_count: 1, blocking_requirement_ids: ["requirement-proof"], task_blocker_count: 1 },
  baselines: [{
    id: "baseline-1",
    project_id: sampleProject.id,
    name: "Initial baseline",
    schema_version: 1,
    completeness: "partial",
    checksum: null,
    source_revision: null,
    created_at: "2026-08-01T00:00:00Z",
    integrity: { status: "partial", verified: false, algorithm: null, missing_facts: ["dependencies"], message: "Legacy partial baseline." },
  }],
};
