import type { ContactDetailPane, ContactDraft, ContactRecord, ContactsView, ModuleStatus } from "../../shared/types";

export type ContactsWorkspaceProps = {
  token: string;
  operational: boolean;
  module?: ModuleStatus;
  contacts: ContactRecord[];
  reviewRows: ContactRecord[];
  selectedContact: ContactRecord | null;
  selectedContactId: string;
  contactsView: ContactsView;
  detailPane: ContactDetailPane;
  query: string;
  statusFilter: string;
  reviewFilter: string;
  typeFilter: string;
  draft: ContactDraft;
  editing: boolean;
  noteText: string;
  relationshipTarget: string;
  relationshipType: string;
  importFilename: string;
  importText: string;
  importBatches: unknown[];
  busyAction: string;
  onActivate: () => void;
  onViewChange: (value: ContactsView) => void;
  onDetailPaneChange: (value: ContactDetailPane) => void;
  onQueryChange: (value: string) => void;
  onStatusFilterChange: (value: string) => void;
  onReviewFilterChange: (value: string) => void;
  onTypeFilterChange: (value: string) => void;
  onSelect: (id: string) => void;
  onCreate: () => void;
  onEdit: () => void;
  onDraftChange: (draft: ContactDraft) => void;
  onSave: () => void;
  onCancelEdit: () => void;
  onArchive: () => void;
  onRestore: () => void;
  onPurge: () => void;
  onNoteTextChange: (value: string) => void;
  onAddNote: () => void;
  onRelationshipTargetChange: (value: string) => void;
  onRelationshipTypeChange: (value: string) => void;
  onLinkRelationship: () => void;
  onImportFilenameChange: (value: string) => void;
  onImportTextChange: (value: string) => void;
  onImport: () => void;
};
