import type { ContactDetailPane, ContactDraft, ContactGroupBy, ContactGroupRecord, ContactRecord, ContactSortBy, ContactSortDir, ContactsView, ModuleStatus } from "../../shared/types";

export type ContactsWorkspaceProps = {
  token: string;
  operational: boolean;
  module?: ModuleStatus;
  contacts: ContactRecord[];
  contactGroups: ContactGroupRecord[];
  selectedContact: ContactRecord | null;
  selectedContactId: string;
  contactsView: ContactsView;
  contactGroupBy: ContactGroupBy;
  contactGroupId: string;
  newGroupName: string;
  detailPane: ContactDetailPane;
  query: string;
  statusFilter: string;
  reviewFilter: string;
  typeFilter: string;
  contactPage: number;
  contactPageSize: number;
  contactHasNext: boolean;
  contactTotalCount: number;
  contactSortBy: ContactSortBy;
  contactSortDir: ContactSortDir;
  draft: ContactDraft;
  editing: boolean;
  noteText: string;
  relationshipTarget: string;
  relationshipType: string;
  busyAction: string;
  onActivate: () => void;
  onViewChange: (value: ContactsView) => void;
  onContactGroupByChange: (value: ContactGroupBy) => void;
  onContactGroupChange: (value: string) => void;
  onDetailPaneChange: (value: ContactDetailPane) => void;
  onQueryChange: (value: string) => void;
  onStatusFilterChange: (value: string) => void;
  onReviewFilterChange: (value: string) => void;
  onTypeFilterChange: (value: string) => void;
  onClearFilters: () => void;
  onContactPageChange: (value: number) => void;
  onContactPageSizeChange: (value: number) => void;
  onContactSortByChange: (value: ContactSortBy) => void;
  onContactSortDirChange: (value: ContactSortDir) => void;
  onSelect: (id: string) => void;
  onCreate: () => void;
  onNewGroupNameChange: (value: string) => void;
  onCreateGroup: () => void;
  onGroupContactsByBusinessDomain: () => void;
  onArchiveGroup: (groupId: string) => void;
  onAddSelectedContactToGroup: (groupId: string) => Promise<void>;
  onRemoveSelectedContactFromGroup: (groupId: string) => Promise<void>;
  onEdit: () => void;
  onInlineUpdate: (field: keyof ContactDraft, value: string) => Promise<void>;
  onDraftChange: (draft: ContactDraft) => void;
  onSave: () => void;
  onCancelEdit: () => void;
  onArchive: () => void;
  onRestore: () => void;
  onPurge: () => void;
  onMarkReady: () => void;
  onNoteTextChange: (value: string) => void;
  onAddNote: () => void;
  onRelationshipTargetChange: (value: string) => void;
  onRelationshipTypeChange: (value: string) => void;
  onLinkRelationship: () => void;
  onUpdateRelationship: (relationshipId: string, fromPartyId: string, toPartyId: string, relationshipType: string) => Promise<void>;
  onRemoveRelationship: (relationshipId: string) => Promise<void>;
  onMergeDuplicate: (primaryContactId: string, duplicateContactId: string) => Promise<void>;
};
