from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
MODULE_ROOT = ROOT / "modules"
OUTPUT_PATH = ROOT / "web" / "src" / "generated" / "moduleSurfaceCatalog.ts"

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from uok.module_contract_validation import validate_module_frontend_contracts  # noqa: E402
from uok.module_manifest_loader import load_module_manifests  # noqa: E402


def ordered_module_names(manifests: dict[str, dict[str, Any]]) -> list[str]:
    ordered: list[str] = []
    visited: set[str] = set()
    visiting: set[str] = set()

    def visit(module_name: str) -> None:
        if module_name in visited:
            return
        if module_name in visiting:
            raise ValueError(f"module dependency cycle includes {module_name}")
        visiting.add(module_name)
        for dependency in sorted(manifests[module_name]["dependencies"]):
            if dependency not in manifests:
                raise ValueError(f"{module_name} depends on unknown module {dependency}")
            visit(dependency)
        visiting.remove(module_name)
        visited.add(module_name)
        ordered.append(module_name)

    for module_name in sorted(manifests):
        visit(module_name)
    return ordered


def render_frontend_module_catalog(module_root: Path = MODULE_ROOT) -> str:
    module_root = module_root.resolve()
    report = validate_module_frontend_contracts(module_root)
    if not report["ok"]:
        details = "; ".join(
            f"{row['module']}:{row['field']}: {row['reason']}"
            for row in report["violations"]
        )
        raise ValueError(f"module frontend contracts are invalid: {details}")

    manifests = load_module_manifests(module_root)
    registrations: list[tuple[str, dict[str, Any]]] = []
    for module_name in ordered_module_names(manifests):
        manifest = manifests[module_name]
        if "web_surface" in manifest["extension_points"]:
            registrations.append((module_name, manifest))
    required_surfaces = [
        (module_name, manifest)
        for module_name, manifest in registrations
        if manifest["required"]
    ]
    if len(required_surfaces) != 1:
        raise ValueError("the required module must declare exactly one frontend surface")
    default_section = required_surfaces[0][1]["web_section"]
    imports = [
        (module_name, manifest, f"moduleSurface{index}")
        for index, (module_name, manifest) in enumerate(registrations)
    ]

    lines = [
        "// Generated by scripts/generate_frontend_module_catalog.py. Do not edit.",
        'import type { GeneratedModuleSurfaceRegistration } from "../features/modules/moduleSurfaceContract";',
        "",
    ]
    for _module_name, manifest, alias in imports:
        entry = Path(manifest["web_entry"]).with_suffix("").as_posix()
        lines.append(f'import {alias} from "../../../{entry}";')
    section_union = " | ".join(
        json.dumps(manifest["web_section"]) for _module_name, manifest, _alias in imports
    )
    lines.extend(
        [
            "",
            f"export type GeneratedModuleSection = {section_union};",
            f"export const defaultModuleSection: GeneratedModuleSection = {json.dumps(default_section)};",
            "",
            "export const generatedModuleSurfaceCatalog = [",
        ]
    )
    for module_name, manifest, alias in imports:
        lines.extend(
            [
                "  {",
                "    manifest: {",
                f"      moduleName: {json.dumps(module_name)},",
                f"      sectionId: {json.dumps(manifest['web_section'])},",
                f"      webEntry: {json.dumps(manifest['web_entry'])},",
                f"      dependencies: {json.dumps(manifest['dependencies'])}",
                "    },",
                f"    surface: {alias}",
                "  },",
            ]
        )
    lines.extend(
        [
            "] as const satisfies readonly GeneratedModuleSurfaceRegistration[];",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the compile-time frontend module catalog.")
    parser.add_argument("--check", action="store_true", help="Fail when the checked-in catalog has drifted.")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()
    try:
        rendered = render_frontend_module_catalog()
    except ValueError as error:
        print(f"Frontend module catalog generation failed: {error}", file=sys.stderr)
        return 1
    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            print(
                f"Frontend module catalog drifted: {output.relative_to(ROOT).as_posix()}",
                file=sys.stderr,
            )
            return 1
        print("Frontend module catalog matches validated manifests.")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Generated {output.relative_to(ROOT).as_posix()}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
